### ISSUE TITLE
Navigation Quick Links in CIDILabs

### ISSUE THREAD

**Issue by honsaar** [UAMediaProd/uoa-styles#49]
These are decided at the theme level but custom content and classes can't be easily injected like content blocks. Would suggest using a CSS/SASS override for the `#kl_navigation` ID when inside the `adx` wrapper class to cut down on as much manual handling in Canvas as possible.

![image](https://user-images.githubusercontent.com/8604678/125718790-caecbc22-492e-4d33-beba-b78e54c2aeb2.png)

Rough idea for styling to match the uoa-styles ideas existing as much as we can, written in CSS at the moment:

```css
#kl_navigation ul > li {
    border: 1px solid #d5d9dd;
    padding: 1em;
    border-radius: 0.5ch 0.5ch 0 0;
    overflow: hidden;
    position: relative;
    transition: all ease 0.2s;
    border-top: 30px solid #d5d9dd;
    font-weight: 700;
    font-family: 'Arial Black','Open Sans', sans-serif;
}

#kl_navigation ul {
    list-style: none;
    min-width: 80%;
    max-width: 100%;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(25ch, 1fr));
    grid-gap: 1ch;
    grid-auto-flow: dense;
    overflow: hidden;
    padding: 1ch;
}

#kl_navigation a {
    color: inherit;
}

#kl_navigation ul > li:hover {
    background: inherit;
    box-shadow: rgb(0 0 0 / 10%) 0px 4px 6px -1px, rgb(0 0 0 / 6%) 0px 2px 4px -1px;
    transform: scale(1.025);
}
```
