### ISSUE TITLE
Tweaks for inbuilt CIDI accordions

### ISSUE THREAD

**Issue by honsaar** [UAMediaProd/uoa-styles#50]
Suggested these overrides for the accordions in use by CIDILabs:

```css
kl_panels_wrapper.ui-accordion .ui-accordion-content p {
    margin: 0;
}

.kl_panels_wrapper .ui-accordion-header, .kl_wrapper .ui-accordion-header {
    background: white;
    border-radius: 0;
    font-size: 1em!important; /* needs to override nests of styles applied by CIDILabs */
}

```
