### ISSUE TITLE
Vanilla Table additions

### ISSUE THREAD

**Issue by honsaar** [UAMediaProd/uoa-styles#51]
For base tables, suggest something like the following to uplift the native Canvas tables to be closer to the adx styled ones.

```css
table td {
    text-align: left;
    border: 1px solid #B9C0C6;
}

table {
    font-size: 1rem;
    min-width: 80%;
    max-width: 100%;
    margin: 1.44rem 0;
    margin-left: auto;
    margin-right: auto;
    border-collapse: separate;
    border-spacing: 0;
}

table tr {
    background: #f9fafa;
}

thead tr {
    border-bottom: 3px solid #B9C0C6;
}
```
