### ISSUE TITLE
Vanilla Quick Check tweaks

### ISSUE THREAD

**Issue by honsaar** [UAMediaProd/uoa-styles#54]
Since quick checks are inbuilt by CIDI we have a limited layout customisation; suggest something small to bring it more in line:

```css
.kl_quick_check {
    box-shadow: rgb(0 0 0 / 10%) 0px 4px 6px -1px, rgb(0 0 0 / 6%) 0px 2px 4px -1px;
    margin: 2.074rem auto;
    border: 1px solid #d5d9dd;
    border-top: solid 2.074rem #102535;
    border-radius: 0.402rem;
    color: #82868b;
}

.kl_quick_check h3 {
    color: #102535;
}
```
